### ISSUE TITLE
issue in php8.0 when pressing on the refresh button

### ISSUE THREAD

**Issue by silviucpp** [ptrofimov/beanstalk_console#178]
```
Fatal error: Uncaught TypeError: fsockopen(): Argument #2 ($port) must be of type int, string given in /srv/www/beanstalk_console/lib/Pheanstalk/Socket/StreamFunctions.php:71 Stack trace: #0 /srv/www/beanstalk_console/lib/Pheanstalk/Socket/StreamFunctions.php(71): fsockopen() #1 /srv/www/beanstalk_console/lib/Pheanstalk/Socket/NativeSocket.php(32): Pheanstalk_Socket_StreamFunctions->fsockopen() #2 /srv/www/beanstalk_console/lib/Pheanstalk/Connection.php(137): Pheanstalk_Socket_NativeSocket->__construct() #3 /srv/www/beanstalk_console/lib/Pheanstalk/Connection.php(70): Pheanstalk_Connection->_getSocket() #4 /srv/www/beanstalk_console/lib/Pheanstalk.php(376): Pheanstalk_Connection->dispatchCommand() #5 /srv/www/beanstalk_console/lib/Pheanstalk.php(113): Pheanstalk->_dispatch() #6 /srv/www/beanstalk_console/lib/BeanstalkInterface.class.php(22): Pheanstalk->listTubes() #7 /srv/www/beanstalk_console/lib/include.php(344): BeanstalkInterface->getTubes() #8 /srv/www/beanstalk_console/lib/include.php(47): Console->_main() #9 /srv/www/beanstalk_console/public/index.php(43): Console->__construct() #10 {main} thrown in /srv/www/beanstalk_console/lib/Pheanstalk/Socket/StreamFunctions.php on line 71
```

**Comment by pentium10** [comment]
I am not able to reconstruct this. How is your server name defined?

**Comment by silviucpp** [comment]
```
 'servers' => array(
                's1.example.com'=>'beanstalk://IP1:11300',
                's2.example.com'=>'beanstalk://IP2:11300', 
                's3.example.com'=>'beanstalk://IP3:11300',
                's4.example.com'=>'beanstalk://IP4:11300'
     ),

```
